CREATE TABLE covid_vaccinations (
  iso_code VARCHAR(10),
  continent VARCHAR(50),
  location VARCHAR(100),
  date DATE,
  total_tests BIGINT,
  new_tests BIGINT,
  total_tests_per_thousand DOUBLE PRECISION,
  new_tests_per_thousand DOUBLE PRECISION,
  new_tests_smoothed BIGINT,
  new_tests_smoothed_per_thousand DOUBLE PRECISION,
  positive_rate DOUBLE PRECISION,
  tests_per_case DOUBLE PRECISION,
  tests_units VARCHAR(50),
  total_vaccinations BIGINT,
  people_vaccinated BIGINT,
  people_fully_vaccinated BIGINT,
  total_boosters BIGINT,
  new_vaccinations BIGINT,
  new_vaccinations_smoothed BIGINT,
  total_vaccinations_per_hundred DOUBLE PRECISION,
  people_vaccinated_per_hundred DOUBLE PRECISION,
  people_fully_vaccinated_per_hundred DOUBLE PRECISION,
  total_boosters_per_hundred DOUBLE PRECISION,
  new_vaccinations_smoothed_per_million INT,
  new_people_vaccinated_smoothed BIGINT,
  new_people_vaccinated_smoothed_per_hundred DOUBLE PRECISION,
  stringency_index DOUBLE PRECISION,
  median_age DOUBLE PRECISION,
  aged_65_older DOUBLE PRECISION,
  aged_70_older DOUBLE PRECISION,
  gdp_per_capita DOUBLE PRECISION,
  extreme_poverty DOUBLE PRECISION,
  cardiovasc_death_rate DOUBLE PRECISION,
  diabetes_prevalence DOUBLE PRECISION,
  female_smokers DOUBLE PRECISION,
  male_smokers DOUBLE PRECISION,
  handwashing_facilities DOUBLE PRECISION,
  hospital_beds_per_thousand DOUBLE PRECISION,
  life_expectancy DOUBLE PRECISION,
  human_development_index DOUBLE PRECISION,
  population BIGINT,
  excess_mortality_cumulative_absolute DOUBLE PRECISION,
  excess_mortality_cumulative DOUBLE PRECISION,
  excess_mortality DOUBLE PRECISION,
  excess_mortality_cumulative_per_million DOUBLE PRECISION
);